# Generated by Django 4.0.5 on 2022-06-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapi', '0009_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='timezone',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
