# Generated by Django 4.0.5 on 2022-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapi', '0010_remove_comment_date_comment_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timezone',
            new_name='date',
        ),
    ]
