# Generated by Django 4.0.5 on 2022-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapi', '0014_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Address',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
